title: EPSRC ARCHANGEL Project
email: j.collomosse@surrey.ac.uk
description: Securing our National Archives for Future Generations
tagline: Securing our National Archives for Future Generations

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.archangel.ac.uk" # the base hostname & protocol for your site, e.g. http://example.com

# twitter_username: jekyllrb
github_username:  archangel-dlt

# Build settings
markdown: kramdown
sass:
    style: compressed
# theme: "ed."
plugins:
  - jekyll-feed
