title: Archangel
email: info@archangel.ac.uk
description: Distributed ledgers to enhance trust in public archives

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# twitter_username: jekyllrb
github_username:  archangel-dlt

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed